name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Registry
        run: |
          echo "${{ secrets.TOKEN }}" | docker login ${{secrets.REGISTRY_URL}} -u ${{ secrets.USER }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{secrets.REGISTRY_URL}}/neok/homelense:latest .

      - name: Push Docker Image
        run: |
          docker push ${{secrets.REGISTRY_URL}}/neok/homelense:latest
